cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :edit]
end

cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birthdate   :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'
class Cat < ApplicationRecord
include ActionView::Helpers::DateHelper
COLORS = [
"brown",
"white",
"black",
"orange",
"purple"
]
    validates :birthdate, :name, :description, presence: true
    validates :sex, inclusion: { in:["M","F"] }, presence: true
    validates :color, inclusion: {in: COLORS}, presence: true
    
    def age
    time_ago_in_words(birthdate)
    end

    def self.color
        COLORS
    end
    
end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        # debugger
        @cats = Cat.all 
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new

        @color = Cat.color
       render :new
    end

    def create
        @age = Cat.find(params[:id]).age #check later
        @cat = Cat.new(cat_params)
        if @cat.persisted?
            redirect_to cat_url(@cat)
        else
            render :new
        end
        
    end

    def edit
        @color = Cat.color
        @cat = Cat.find(params[:id])
        render :edit
    end

    private

    def cat_params
        params.require(:cat).permit(:name, :birthdate, :sex, :color, :description)
    end
end

=begin
    <form action="<%= cats_url %>" method= "POST">

    <label>Name:
        <input type="text" name="cats[name]">
    </label>

    <label>Purrrthday:
        <input type="date" name="cats[birthdate]">
    </label>

    <label for="color">Color:
        <select id = "color" name="cats[color]">
                <option value="default">Select a Color</option>
            <%@color.each do |color|%>
                <option value="<%color%>"><%=color%></option>
            <%end%>
        </select>
    </label>
    <label>Sex:
        <label for="Male">Male:
            <input type="radio" id="Male" name="sex" value = "M">
        </label>
        <label for="Female">Female:
            <input type="radio" id="Female" name="sex" value = "F">
        </label>
    </label>
    <label>Description:    
        <textarea name="cats[description]" ></textarea>
    </label>



    <button>Click me</button>
</form>

    
=end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/views/cats/_form.html.erb
<<% if action == "edit" %>>
<form action="<%=edit_cat_url(cat)%>" method= "POST">
<input type="hidden" name="_method" value="PATCH">
<% else %> 
<form action="<%=new_cat_url %>" method= "POST">
<<% end %>>

    <label>Name:
        <input type="text" name="cats[name]" value="<%=cat.name%>">
    </label>

    <label>Purrrthday:
        <input type="date" name="cats[birthdate]" value="<%=cat.birthdate%>"> 
    </label>

    <label for="color">Color:
        <select id = "color" name="cats[color]">
                <option value="default">Select a Color</option>
            <%@color.each do |color|%>
                <% if cat.color == color %>
                    <option value="<%color%>" selected><%=color%></option>
                <% else %>
                    <option value="<%color%>"><%=color%></option>
                <% end %>
            <%end%>
        </select>
    </label>
    <label>Sex:
        <%if cat.sex == "M"%>
            <label for="Male">Male:
                <input type="radio" id="Male" name="sex" value = "M" checked>
            </label>
            <label for="Female">Female:
                <input type="radio" id="Female" name="sex" value = "F">
            </label>
        <%else %>
            <label for="Male">Male:
                <input type="radio" id="Male" name="sex" value = "M">
            </label>
            <label for="Female">Female:
                <input type="radio" id="Female" name="sex" value = "F" checked>
            </label>
        <%end%>
    </label>
    <label>Description:    
        <textarea name="cats[description]" ><%=cat.description%></textarea>
    </label>



    <button>Click me</button>
</form>

cats/app/views/cats/edit.html.erb
<h1>Edit me purrty pwease</h1>
<%= render 'form',cat: @cat action="edit"%>

cats/app/views/cats/index.html.erb
<h1>These are our <em>fabulous</em> cats!</h1>

<ul>
    <% @cats.each do |cat| %>
        <li><%= cat.name %></li>
        <li><a href="<%=cat_url(cat)%>">Check me-owt!</a></li>
        <%#= render "cat", cat: cat %>
    <% end %>
</ul>

cats/app/views/cats/new.html.erb
<h1>Mew Form</h1>
<%= render 'form',cat: @cat, action="new" %>

cats/app/views/cats/show.html.erb
<h1>Hey, it's me <%= @cat.name %> =^.^=</h1>

<table>
    <thead>
        <tr>
            <th>About me</th>
        </tr>
    </thead>

    <tbody>
        <tr> <% [:name, :birthdate, :sex, :color, :description].each do |attribute| %>
            <td><%= attribute %></td>
            <td><%= @cat.send attribute %></td>
        </tr>
        <% end %>
    </tbody>
</table>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>